basePath: /
host: localhost:4000
info:
  contact:
    name: Dev Support
  description: 'Backend для проекта "JedelKomek": работа с пользователями, инцидентами,
    уведомлениями и экстренными вызовами'
  title: JedelKomek API
  version: "1.0"
paths: {}
swagger: "2.0"
